management.endpoints.web.exposure.include: bindings,metrics


spring:
  cloud:
    stream:

      bindings:
        tradesEmitter:
          destination: trades
          binder: local_rabbit

        trades:  # com.pivotal.partitioning.TRADES
          destination: trades
          binder: local_rabbit
          group: trades_group

        tradeConfirmations:  # com.pivotal.partitioning.TRADE_CONFIRMATION
          destination: trade_confirmations
          binder: local_rabbit

        tradeConfirmationEmitter:
          destination: trade_confirmations
          binder: local_rabbit

      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
