management:
  endpoint:
    health.show-details: always
  endpoints.web.exposure.include: metrics, health, configprops, env, integrationgraph


spring:
  cloud:
    stream:

      bindings:
        trades:  # com.pivotal.partitioning.TRADES
          destination: trades
          binder: local_rabbit
          group: trades_group

          consumer:
            partitioned: true


      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
